version: "3"
networks:
  web:
services:
  mysql:
    image: mysql:5.7.13
    command: --max_allowed_packet=200000000
    volumes:
      - C:\data\website:/var/lib/mysql
    networks:
      - web
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: website
    ports:
      - 3307:3306
